### ISSUE TITLE
dm04 changing names

### ISSUE THREAD

**Issue by jarvisc1** [jarvisc1/comix_data_clean#3]
For renaming variables, we read in a file and it changes the names in step 4. 

- [ ]  We need to check if we're keeping all variables. 
- [ ]  Change some of the names that are really long

**Comment by wongkerry** [comment]
Found duplicates in var_name csv which might be errors?
q52_10_scale appears twice in var column and ipsos_varname column, and q66_loop_100_q71_12 appears twice in ipsos_varname column (but perhaps this one is okay...?); print screens in var_name.csv (similar in var_name2.csv, except q52_10_scale do not have new names) -

![image](https://user-images.githubusercontent.com/41377220/98674540-ddc58f80-2350-11eb-8788-8d655e3bb046.png)

![image](https://user-images.githubusercontent.com/41377220/98674633-0057a880-2351-11eb-8add-d9ee1e43e393.png)

**Comment by wongkerry** [comment]
Is this part dropping variables that should not be dropped? 

`c_codes <- c(be = "be", uk = "uk", nl = "nl", no = "no")`
`remove <- paste(setdiff(c_codes, c_code), collapse = "|")`
`keep <- grep(remove, varnames$var, invert = T, value = T)`
`varnames <- varnames[var %in% keep]`

E.g., if c_code/country was "uk", `gender_nonbinary` and `educat_no` are getting dropped, which have new names `part_gender_nb` and  `part_education`

**Comment by wongkerry** [comment]
> Is this part dropping variables that should not be dropped?
> 
> `c_codes <- c(be = "be", uk = "uk", nl = "nl", no = "no")`
> `remove <- paste(setdiff(c_codes, c_code), collapse = "|")`
> `keep <- grep(remove, varnames$var, invert = T, value = T)`
> `varnames <- varnames[var %in% keep]`
> 
> E.g., if c_code/country was "uk", `gender_nonbinary` and `educat_no` are getting dropped, which have new names `part_gender_nb` and `part_education`

**Comment by wongkerry** [comment]
> Found duplicates in var_name csv which might be errors?
> q52_10_scale appears twice in var column and ipsos_varname column, and q66_loop_100_q71_12 appears twice in ipsos_varname column (but perhaps this one is okay...?); print screens in var_name.csv (similar in var_name2.csv, except q52_10_scale do not have new names) -
> 
> ![image](https://user-images.githubusercontent.com/41377220/98674540-ddc58f80-2350-11eb-8788-8d655e3bb046.png)
> 
> ![image](https://user-images.githubusercontent.com/41377220/98674633-0057a880-2351-11eb-8add-d9ee1e43e393.png)

No need to worry about duplicated q66_loop_100_q71_12, since ipsos_varname col is not used. 

For q52_10_scale, am inclined to think that line 219 in excel image is not needed after checking variable label from SPSS file (I opened in Stata)
![image](https://user-images.githubusercontent.com/41377220/98799453-0b6d1000-2407-11eb-9fbe-bd837f977c83.png)
Seems like just a change of mind what to call q52_10_scale to be i line with q52_9_scale (over_100).

**Comment by wongkerry** [comment]
dm04_rename_vars.R, line 50: after using var_names.xlsx to rename, q20 should become hh_size, so line 50 should never find q20, in which case line 50 makes a null variable called q20_new

**Comment by wongkerry** [comment]
Confirm the below for var_names.xlsx, sheet "survey_2":

1. rename insq26a to 0. 
2. rename q29_10 to no answers for symptoms. seems to be Nausea or vomiting from spss?
3. rename q32 to "hhm_covid_test_recent" and q32a to "part_covid_test_past". should both be recent (or past)?

**Comment by wongkerry** [comment]
Okay for the set of hhm_symp_ variables (newname) across survey_1 and survey_2 to not be spelt consistently? e.g, sore throat is hhm_symp_sore_throat in survey_2 and hhm_symp_st in survey_1

**Comment by wongkerry** [comment]
Confirm the below for var_names.xlsx, sheet "survey_1":

1. rename q50_14 to hhm_close_childcare_school and q51_14 to hhm_not_attend_childcare_school_care. I think they are the same and perhaps should be renamed consistently.

**Comment by jarvisc1** [comment]
1. insq26a. I'm not sure what this is happy for it to be 0
2. q29_10 is Prefer not to answer for the early surveys. I can see now that it is Nausea or vommiting for the new one. Yes please change for survey 2.
3. They;re not the same one is last 14 days the other is before the last 14 days. 
 Q32. Has NAME been tested for Coronavirus (Covid-19) via a nose and/or throat swab in the last fourteen days?
Q32a. Have you been tested for Coronavirus (Covid-19) via a nose and/or throat swab prior to the past fourteen days?


We want the variables to be spelt consistently across survey 1 and 2. Can you change that please? sore_throat make more sense than st. 



Q50 and 51 are different. 
q50 was whether the childcare due to a school being closed due to coronavirus.
q51  was whether the child did not attend due to cornanvirus

**Comment by wongkerry** [comment]
insq26a is in UK panels E and F; value label consists of the following: pre-school or nursery; school; secondary school; their university or other higher educational institution

**Comment by wongkerry** [comment]
(chris can ignore) my list: part_employ_type, part_social_group(1)(2)

**Comment by jarvisc1** [comment]
Okay does insq26a correspond to a previously asked question?

**Comment by wongkerry** [comment]
In addition to sore throat (hhm_symp):
- hhm_symp_dk (survey 1) and hhm_symp_dont_know (survey 2). changing S2 to match with S1
- hhm_symp_no_answer (survey 1) and hhm_symp_prefer_not_to_answer (survey 2). changing S1 to match with S2
